### ISSUE TITLE
🐛 2016-03-27-gladys-et-docker.md Need update

### ISSUE THREAD

**Issue by VonOx** [GladysProject/gladysproject.com.jekyll#5]
The latest image of mysql used in this article doesnt work anymore

MySQL introduce some breaking change in V8 related to authenctication

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

Suggests:

-  Using mysql image supported ( `mysql:5` )
- Using `mysql:latest` but with option `--default-authentication-plugin=mysql_native_password`
- Using mariadb image ( mysql fork / open source )

What do you think ?

PS: Other repo need to be updated too.

**Comment by Pierre-Gilles** [comment]
I would suggest switching to MariaDB as we switched to MariaDB on the Raspbian image :)

**Comment by Pierre-Gilles** [comment]
Merged! Thanks for your PR :)
